// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * AgentCard
 *
 * A2A Agent Card.
 */
export type AgentCard = {
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description: string;
    /**
     * Url
     */
    url: string;
    /**
     * Version
     */
    version?: string;
    /**
     * Capabilities
     */
    capabilities?: {
        [key: string]: unknown;
    };
    /**
     * Skills
     */
    skills?: Array<{
        [key: string]: unknown;
    }>;
};

/**
 * AgentCreate
 *
 * エージェント作成リクエスト.
 */
export type AgentCreate = {
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * System Prompt
     */
    system_prompt: string;
    /**
     * Llm Provider
     */
    llm_provider: string;
    /**
     * Llm Model
     */
    llm_model: string;
    /**
     * Tools
     */
    tools?: Array<string>;
    /**
     * A2A Enabled
     */
    a2a_enabled?: boolean;
};

/**
 * AgentResponse
 *
 * エージェントレスポンス.
 */
export type AgentResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * User Id
     */
    user_id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description: string | null;
    /**
     * System Prompt
     */
    system_prompt: string;
    /**
     * Llm Provider
     */
    llm_provider: string;
    /**
     * Llm Model
     */
    llm_model: string;
    /**
     * Tools
     */
    tools: Array<string>;
    /**
     * A2A Enabled
     */
    a2a_enabled: boolean;
};

/**
 * AgentUpdate
 *
 * エージェント更新リクエスト.
 */
export type AgentUpdate = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Description
     */
    description?: string | null;
    /**
     * System Prompt
     */
    system_prompt?: string | null;
    /**
     * Llm Provider
     */
    llm_provider?: string | null;
    /**
     * Llm Model
     */
    llm_model?: string | null;
    /**
     * Tools
     */
    tools?: Array<string> | null;
    /**
     * A2A Enabled
     */
    a2a_enabled?: boolean | null;
};

/**
 * ChatMessage
 *
 * チャットメッセージ.
 */
export type ChatMessage = {
    /**
     * Role
     */
    role: string;
    /**
     * Content
     */
    content: string;
};

/**
 * ChatRequest
 *
 * チャットリクエスト.
 */
export type ChatRequest = {
    /**
     * Agent Id
     */
    agent_id: string;
    /**
     * Conversation Id
     */
    conversation_id?: string | null;
    /**
     * Message
     */
    message: string;
};

/**
 * ChatResponse
 *
 * チャットレスポンス.
 */
export type ChatResponse = {
    /**
     * Conversation Id
     */
    conversation_id: string;
    message: ChatMessage;
    /**
     * Tool Calls
     */
    tool_calls?: Array<{
        [key: string]: unknown;
    }> | null;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * TaskRequest
 *
 * A2Aタスクリクエスト.
 */
export type TaskRequest = {
    /**
     * Id
     */
    id: string;
    /**
     * Message
     */
    message: {
        [key: string]: unknown;
    };
};

/**
 * TaskResponse
 *
 * A2Aタスクレスポンス.
 */
export type TaskResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Status
     */
    status: string;
    /**
     * Result
     */
    result?: {
        [key: string]: unknown;
    } | null;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

export type ListAgentsApiAgentsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/agents';
};

export type ListAgentsApiAgentsGetResponses = {
    /**
     * Response List Agents Api Agents Get
     *
     * Successful Response
     */
    200: Array<AgentResponse>;
};

export type ListAgentsApiAgentsGetResponse = ListAgentsApiAgentsGetResponses[keyof ListAgentsApiAgentsGetResponses];

export type CreateAgentApiAgentsPostData = {
    body: AgentCreate;
    path?: never;
    query?: never;
    url: '/api/agents';
};

export type CreateAgentApiAgentsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateAgentApiAgentsPostError = CreateAgentApiAgentsPostErrors[keyof CreateAgentApiAgentsPostErrors];

export type CreateAgentApiAgentsPostResponses = {
    /**
     * Successful Response
     */
    200: AgentResponse;
};

export type CreateAgentApiAgentsPostResponse = CreateAgentApiAgentsPostResponses[keyof CreateAgentApiAgentsPostResponses];

export type DeleteAgentApiAgentsAgentIdDeleteData = {
    body?: never;
    path: {
        /**
         * Agent Id
         */
        agent_id: string;
    };
    query?: never;
    url: '/api/agents/{agent_id}';
};

export type DeleteAgentApiAgentsAgentIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteAgentApiAgentsAgentIdDeleteError = DeleteAgentApiAgentsAgentIdDeleteErrors[keyof DeleteAgentApiAgentsAgentIdDeleteErrors];

export type DeleteAgentApiAgentsAgentIdDeleteResponses = {
    /**
     * Response Delete Agent Api Agents  Agent Id  Delete
     *
     * Successful Response
     */
    200: {
        [key: string]: string;
    };
};

export type DeleteAgentApiAgentsAgentIdDeleteResponse = DeleteAgentApiAgentsAgentIdDeleteResponses[keyof DeleteAgentApiAgentsAgentIdDeleteResponses];

export type GetAgentApiAgentsAgentIdGetData = {
    body?: never;
    path: {
        /**
         * Agent Id
         */
        agent_id: string;
    };
    query?: never;
    url: '/api/agents/{agent_id}';
};

export type GetAgentApiAgentsAgentIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetAgentApiAgentsAgentIdGetError = GetAgentApiAgentsAgentIdGetErrors[keyof GetAgentApiAgentsAgentIdGetErrors];

export type GetAgentApiAgentsAgentIdGetResponses = {
    /**
     * Successful Response
     */
    200: AgentResponse;
};

export type GetAgentApiAgentsAgentIdGetResponse = GetAgentApiAgentsAgentIdGetResponses[keyof GetAgentApiAgentsAgentIdGetResponses];

export type UpdateAgentApiAgentsAgentIdPatchData = {
    body: AgentUpdate;
    path: {
        /**
         * Agent Id
         */
        agent_id: string;
    };
    query?: never;
    url: '/api/agents/{agent_id}';
};

export type UpdateAgentApiAgentsAgentIdPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateAgentApiAgentsAgentIdPatchError = UpdateAgentApiAgentsAgentIdPatchErrors[keyof UpdateAgentApiAgentsAgentIdPatchErrors];

export type UpdateAgentApiAgentsAgentIdPatchResponses = {
    /**
     * Successful Response
     */
    200: AgentResponse;
};

export type UpdateAgentApiAgentsAgentIdPatchResponse = UpdateAgentApiAgentsAgentIdPatchResponses[keyof UpdateAgentApiAgentsAgentIdPatchResponses];

export type ChatApiChatPostData = {
    body: ChatRequest;
    path?: never;
    query?: never;
    url: '/api/chat';
};

export type ChatApiChatPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ChatApiChatPostError = ChatApiChatPostErrors[keyof ChatApiChatPostErrors];

export type ChatApiChatPostResponses = {
    /**
     * Successful Response
     */
    200: ChatResponse;
};

export type ChatApiChatPostResponse = ChatApiChatPostResponses[keyof ChatApiChatPostResponses];

export type ChatStreamApiChatStreamPostData = {
    body: ChatRequest;
    path?: never;
    query?: never;
    url: '/api/chat/stream';
};

export type ChatStreamApiChatStreamPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ChatStreamApiChatStreamPostError = ChatStreamApiChatStreamPostErrors[keyof ChatStreamApiChatStreamPostErrors];

export type ChatStreamApiChatStreamPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetConversationApiChatConversationsConversationIdGetData = {
    body?: never;
    path: {
        /**
         * Conversation Id
         */
        conversation_id: string;
    };
    query?: never;
    url: '/api/chat/conversations/{conversation_id}';
};

export type GetConversationApiChatConversationsConversationIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetConversationApiChatConversationsConversationIdGetError = GetConversationApiChatConversationsConversationIdGetErrors[keyof GetConversationApiChatConversationsConversationIdGetErrors];

export type GetConversationApiChatConversationsConversationIdGetResponses = {
    /**
     * Response Get Conversation Api Chat Conversations  Conversation Id  Get
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type GetConversationApiChatConversationsConversationIdGetResponse = GetConversationApiChatConversationsConversationIdGetResponses[keyof GetConversationApiChatConversationsConversationIdGetResponses];

export type ListConversationsApiChatConversationsGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Agent Id
         */
        agent_id?: string | null;
    };
    url: '/api/chat/conversations';
};

export type ListConversationsApiChatConversationsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListConversationsApiChatConversationsGetError = ListConversationsApiChatConversationsGetErrors[keyof ListConversationsApiChatConversationsGetErrors];

export type ListConversationsApiChatConversationsGetResponses = {
    /**
     * Response List Conversations Api Chat Conversations Get
     *
     * Successful Response
     */
    200: Array<{
        [key: string]: unknown;
    }>;
};

export type ListConversationsApiChatConversationsGetResponse = ListConversationsApiChatConversationsGetResponses[keyof ListConversationsApiChatConversationsGetResponses];

export type GetAgentCardA2aAgentsAgentIdWellKnownAgentJsonGetData = {
    body?: never;
    path: {
        /**
         * Agent Id
         */
        agent_id: string;
    };
    query?: never;
    url: '/a2a/agents/{agent_id}/.well-known/agent.json';
};

export type GetAgentCardA2aAgentsAgentIdWellKnownAgentJsonGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetAgentCardA2aAgentsAgentIdWellKnownAgentJsonGetError = GetAgentCardA2aAgentsAgentIdWellKnownAgentJsonGetErrors[keyof GetAgentCardA2aAgentsAgentIdWellKnownAgentJsonGetErrors];

export type GetAgentCardA2aAgentsAgentIdWellKnownAgentJsonGetResponses = {
    /**
     * Successful Response
     */
    200: AgentCard;
};

export type GetAgentCardA2aAgentsAgentIdWellKnownAgentJsonGetResponse = GetAgentCardA2aAgentsAgentIdWellKnownAgentJsonGetResponses[keyof GetAgentCardA2aAgentsAgentIdWellKnownAgentJsonGetResponses];

export type CreateTaskA2aAgentsAgentIdTasksPostData = {
    body: TaskRequest;
    path: {
        /**
         * Agent Id
         */
        agent_id: string;
    };
    query?: never;
    url: '/a2a/agents/{agent_id}/tasks';
};

export type CreateTaskA2aAgentsAgentIdTasksPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateTaskA2aAgentsAgentIdTasksPostError = CreateTaskA2aAgentsAgentIdTasksPostErrors[keyof CreateTaskA2aAgentsAgentIdTasksPostErrors];

export type CreateTaskA2aAgentsAgentIdTasksPostResponses = {
    /**
     * Successful Response
     */
    200: TaskResponse;
};

export type CreateTaskA2aAgentsAgentIdTasksPostResponse = CreateTaskA2aAgentsAgentIdTasksPostResponses[keyof CreateTaskA2aAgentsAgentIdTasksPostResponses];

export type GetTaskA2aAgentsAgentIdTasksTaskIdGetData = {
    body?: never;
    path: {
        /**
         * Agent Id
         */
        agent_id: string;
        /**
         * Task Id
         */
        task_id: string;
    };
    query?: never;
    url: '/a2a/agents/{agent_id}/tasks/{task_id}';
};

export type GetTaskA2aAgentsAgentIdTasksTaskIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetTaskA2aAgentsAgentIdTasksTaskIdGetError = GetTaskA2aAgentsAgentIdTasksTaskIdGetErrors[keyof GetTaskA2aAgentsAgentIdTasksTaskIdGetErrors];

export type GetTaskA2aAgentsAgentIdTasksTaskIdGetResponses = {
    /**
     * Successful Response
     */
    200: TaskResponse;
};

export type GetTaskA2aAgentsAgentIdTasksTaskIdGetResponse = GetTaskA2aAgentsAgentIdTasksTaskIdGetResponses[keyof GetTaskA2aAgentsAgentIdTasksTaskIdGetResponses];

export type CancelTaskA2aAgentsAgentIdTasksTaskIdCancelPostData = {
    body?: never;
    path: {
        /**
         * Agent Id
         */
        agent_id: string;
        /**
         * Task Id
         */
        task_id: string;
    };
    query?: never;
    url: '/a2a/agents/{agent_id}/tasks/{task_id}/cancel';
};

export type CancelTaskA2aAgentsAgentIdTasksTaskIdCancelPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CancelTaskA2aAgentsAgentIdTasksTaskIdCancelPostError = CancelTaskA2aAgentsAgentIdTasksTaskIdCancelPostErrors[keyof CancelTaskA2aAgentsAgentIdTasksTaskIdCancelPostErrors];

export type CancelTaskA2aAgentsAgentIdTasksTaskIdCancelPostResponses = {
    /**
     * Successful Response
     */
    200: TaskResponse;
};

export type CancelTaskA2aAgentsAgentIdTasksTaskIdCancelPostResponse = CancelTaskA2aAgentsAgentIdTasksTaskIdCancelPostResponses[keyof CancelTaskA2aAgentsAgentIdTasksTaskIdCancelPostResponses];

export type HealthCheckHealthGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type HealthCheckHealthGetResponses = {
    /**
     * Response Health Check Health Get
     *
     * Successful Response
     */
    200: {
        [key: string]: string;
    };
};

export type HealthCheckHealthGetResponse = HealthCheckHealthGetResponses[keyof HealthCheckHealthGetResponses];
