// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * AgentCard
 *
 * A2A Agent Card.
 */
export type AgentCard = {
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description: string;
    /**
     * Url
     */
    url: string;
    /**
     * Version
     */
    version?: string;
    /**
     * Protocolversion
     */
    protocolVersion?: string;
    /**
     * Capabilities
     */
    capabilities?: {
        [key: string]: unknown;
    };
    /**
     * Skills
     */
    skills?: Array<{
        [key: string]: unknown;
    }>;
    /**
     * Defaultinputmodes
     */
    defaultInputModes?: Array<string>;
    /**
     * Defaultoutputmodes
     */
    defaultOutputModes?: Array<string>;
    /**
     * Provider
     */
    provider?: {
        [key: string]: string;
    } | null;
};

/**
 * AgentCreate
 *
 * エージェント作成リクエスト.
 */
export type AgentCreate = {
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * System Prompt
     */
    system_prompt: string;
    /**
     * Llm Provider
     */
    llm_provider: string;
    /**
     * Llm Model
     */
    llm_model: string;
    /**
     * Tools
     */
    tools?: Array<string>;
    /**
     * A2A Enabled
     */
    a2a_enabled?: boolean;
};

/**
 * AgentResponse
 *
 * エージェントレスポンス.
 */
export type AgentResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * User Id
     */
    user_id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description: string | null;
    /**
     * System Prompt
     */
    system_prompt: string;
    /**
     * Llm Provider
     */
    llm_provider: string;
    /**
     * Llm Model
     */
    llm_model: string;
    /**
     * Tools
     */
    tools: Array<string>;
    /**
     * A2A Enabled
     */
    a2a_enabled: boolean;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * AgentUpdate
 *
 * エージェント更新リクエスト.
 */
export type AgentUpdate = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Description
     */
    description?: string | null;
    /**
     * System Prompt
     */
    system_prompt?: string | null;
    /**
     * Llm Provider
     */
    llm_provider?: string | null;
    /**
     * Llm Model
     */
    llm_model?: string | null;
    /**
     * Tools
     */
    tools?: Array<string> | null;
    /**
     * A2A Enabled
     */
    a2a_enabled?: boolean | null;
};

/**
 * ApiTriggerErrorResponse
 *
 * API Trigger エラーレスポンス.
 */
export type ApiTriggerErrorResponse = {
    /**
     * Detail
     */
    detail: string;
};

/**
 * ApiTriggerRequest
 *
 * API Trigger リクエスト.
 */
export type ApiTriggerRequest = {
    /**
     * Trigger Data
     */
    trigger_data?: {
        [key: string]: unknown;
    } | null;
};

/**
 * ApiTriggerResponse
 *
 * API Trigger レスポンス.
 */
export type ApiTriggerResponse = {
    /**
     * Status
     */
    status: string;
    /**
     * Task Id
     */
    task_id: string;
    /**
     * Workflow Id
     */
    workflow_id: string;
    /**
     * Rate Limit Remaining
     */
    rate_limit_remaining: number;
};

/**
 * ChatMessageResponse
 *
 * チャットメッセージ.
 */
export type ChatMessageResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Role
     */
    role: string;
    /**
     * Content
     */
    content: string;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * ChatRequest
 *
 * チャットリクエスト.
 */
export type ChatRequest = {
    /**
     * Agent Id
     */
    agent_id: string;
    /**
     * Conversation Id
     */
    conversation_id?: string | null;
    /**
     * Message
     */
    message: string;
};

/**
 * ChatResponse
 *
 * チャットレスポンス.
 */
export type ChatResponse = {
    /**
     * Conversation Id
     */
    conversation_id: string;
    message: ChatMessageResponse;
};

/**
 * ConversationResponse
 *
 * 会話レスポンス.
 */
export type ConversationResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Agent Id
     */
    agent_id: string;
    /**
     * User Id
     */
    user_id: string;
    /**
     * Title
     */
    title: string | null;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * ConversationWithMessagesResponse
 *
 * 会話とメッセージのレスポンス.
 */
export type ConversationWithMessagesResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Agent Id
     */
    agent_id: string;
    /**
     * User Id
     */
    user_id: string;
    /**
     * Title
     */
    title: string | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Messages
     */
    messages: Array<ChatMessageResponse>;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * MessagePart
 *
 * A2Aメッセージパート.
 */
export type MessagePart = {
    /**
     * Type
     */
    type?: string;
    /**
     * Text
     */
    text: string;
};

/**
 * NodePosition
 *
 * ノード位置.
 */
export type NodePosition = {
    /**
     * X
     */
    x: number;
    /**
     * Y
     */
    y: number;
};

/**
 * PersonalAgentCreate
 *
 * Personal Agent作成リクエスト.
 */
export type PersonalAgentCreate = {
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * System Prompt
     */
    system_prompt: string;
    /**
     * Is Public
     */
    is_public?: boolean;
};

/**
 * PersonalAgentResponse
 *
 * Personal Agentレスポンス.
 */
export type PersonalAgentResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * User Id
     */
    user_id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description: string | null;
    /**
     * System Prompt
     */
    system_prompt: string;
    /**
     * Is Public
     */
    is_public: boolean;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * PersonalAgentUpdate
 *
 * Personal Agent更新リクエスト.
 */
export type PersonalAgentUpdate = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Description
     */
    description?: string | null;
    /**
     * System Prompt
     */
    system_prompt?: string | null;
    /**
     * Is Public
     */
    is_public?: boolean | null;
};

/**
 * ScheduleTriggerCreate
 *
 * スケジュールトリガー作成リクエスト.
 */
export type ScheduleTriggerCreate = {
    /**
     * Cron Expression
     *
     * cron式 (例: '0 9 * * *')
     */
    cron_expression: string;
    /**
     * Timezone
     *
     * タイムゾーン
     */
    timezone?: string;
};

/**
 * ScheduleTriggerResponse
 *
 * スケジュールトリガーレスポンス.
 */
export type ScheduleTriggerResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Workflow Id
     */
    workflow_id: string;
    /**
     * Cron Expression
     */
    cron_expression: string;
    /**
     * Timezone
     */
    timezone: string;
    /**
     * Is Active
     */
    is_active: boolean;
    /**
     * Last Run At
     */
    last_run_at: string | null;
    /**
     * Next Run At
     */
    next_run_at: string | null;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * ScheduleTriggerToggle
 *
 * スケジュールトリガー有効/無効切り替え.
 */
export type ScheduleTriggerToggle = {
    /**
     * Is Active
     */
    is_active: boolean;
};

/**
 * TaskMessage
 *
 * A2Aタスクメッセージ.
 */
export type TaskMessage = {
    /**
     * Role
     */
    role?: string;
    /**
     * Parts
     */
    parts: Array<MessagePart | {
        [key: string]: unknown;
    }>;
};

/**
 * TaskRequest
 *
 * A2Aタスクリクエスト.
 */
export type TaskRequest = {
    /**
     * Id
     */
    id?: string | null;
    message: TaskMessage;
};

/**
 * TaskResponse
 *
 * A2Aタスクレスポンス.
 */
export type TaskResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Status
     */
    status: string;
    result?: TaskResult | null;
    /**
     * Error
     */
    error?: string | null;
    /**
     * Agent Id
     */
    agent_id?: string | null;
};

/**
 * TaskResult
 *
 * A2Aタスク結果.
 */
export type TaskResult = {
    message?: TaskResultMessage | null;
};

/**
 * TaskResultMessage
 *
 * A2Aタスク結果メッセージ.
 */
export type TaskResultMessage = {
    /**
     * Role
     */
    role: string;
    /**
     * Parts
     */
    parts: Array<{
        [key: string]: unknown;
    }>;
};

/**
 * UserApiKeyCreate
 *
 * API Key作成リクエスト.
 */
export type UserApiKeyCreate = {
    /**
     * Name
     */
    name: string;
    /**
     * Scopes
     */
    scopes?: Array<string>;
    /**
     * Rate Limit
     */
    rate_limit?: number;
    /**
     * Expires At
     */
    expires_at?: string | null;
};

/**
 * UserApiKeyCreated
 *
 * API Key作成レスポンス（生キー含む、作成時のみ）.
 */
export type UserApiKeyCreated = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Key
     */
    key: string;
    /**
     * Key Prefix
     */
    key_prefix: string;
    /**
     * Scopes
     */
    scopes: Array<string>;
    /**
     * Rate Limit
     */
    rate_limit: number;
    /**
     * Expires At
     */
    expires_at: string | null;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * UserApiKeyResponse
 *
 * API Keyレスポンス（一覧表示用、生キーなし）.
 */
export type UserApiKeyResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * User Id
     */
    user_id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Key Prefix
     */
    key_prefix: string;
    /**
     * Scopes
     */
    scopes: Array<string>;
    /**
     * Rate Limit
     */
    rate_limit: number;
    /**
     * Expires At
     */
    expires_at: string | null;
    /**
     * Last Used At
     */
    last_used_at: string | null;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * UserLLMConfigCreate
 *
 * LLM Config作成リクエスト.
 */
export type UserLlmConfigCreate = {
    /**
     * Provider
     */
    provider: string;
    /**
     * Api Key
     */
    api_key: string;
    /**
     * Is Default
     */
    is_default?: boolean;
};

/**
 * UserLLMConfigResponse
 *
 * LLM Configレスポンス.
 */
export type UserLlmConfigResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * User Id
     */
    user_id: string;
    /**
     * Provider
     */
    provider: string;
    /**
     * Is Default
     */
    is_default: boolean;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

/**
 * WebhookErrorResponse
 *
 * Webhookエラーレスポンス.
 */
export type WebhookErrorResponse = {
    /**
     * Detail
     */
    detail: string;
};

/**
 * WebhookResponse
 *
 * Webhook実行レスポンス.
 */
export type WebhookResponse = {
    /**
     * Status
     */
    status: string;
    /**
     * Task Id
     */
    task_id: string;
    /**
     * Workflow Id
     */
    workflow_id: string;
};

/**
 * WebhookTriggerCreate
 *
 * Webhookトリガー作成リクエスト.
 */
export type WebhookTriggerCreate = {
    /**
     * Webhook Path
     *
     * Webhookパス (例: 'my-workflow-hook')
     */
    webhook_path: string;
};

/**
 * WebhookTriggerResponse
 *
 * Webhookトリガーレスポンス.
 */
export type WebhookTriggerResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Workflow Id
     */
    workflow_id: string;
    /**
     * Webhook Path
     */
    webhook_path: string;
    /**
     * Secret
     */
    secret: string | null;
    /**
     * Is Active
     */
    is_active: boolean;
    /**
     * Last Triggered At
     */
    last_triggered_at: string | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Webhook Url
     */
    webhook_url: string;
};

/**
 * WebhookTriggerSecretResponse
 *
 * Webhookシークレット再生成レスポンス.
 */
export type WebhookTriggerSecretResponse = {
    /**
     * Secret
     */
    secret: string;
};

/**
 * WorkflowCreate
 *
 * Workflow作成リクエスト.
 */
export type WorkflowCreate = {
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Nodes
     */
    nodes?: Array<WorkflowNode>;
    /**
     * Edges
     */
    edges?: Array<WorkflowEdge>;
    /**
     * Trigger Config
     */
    trigger_config?: {
        [key: string]: unknown;
    };
};

/**
 * WorkflowEdge
 *
 * ワークフローエッジ.
 */
export type WorkflowEdge = {
    /**
     * Id
     */
    id: string;
    /**
     * Source
     */
    source: string;
    /**
     * Target
     */
    target: string;
    /**
     * Sourcehandle
     */
    sourceHandle?: string | null;
    /**
     * Targethandle
     */
    targetHandle?: string | null;
};

/**
 * WorkflowExecutionCreate
 *
 * Workflow実行リクエスト.
 */
export type WorkflowExecutionCreate = {
    /**
     * Trigger Data
     */
    trigger_data?: {
        [key: string]: unknown;
    } | null;
};

/**
 * WorkflowExecutionResponse
 *
 * Workflow実行レスポンス.
 */
export type WorkflowExecutionResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Workflow Id
     */
    workflow_id: string;
    /**
     * Status
     */
    status: string;
    /**
     * Trigger Data
     */
    trigger_data: {
        [key: string]: unknown;
    } | null;
    /**
     * Node Results
     */
    node_results: {
        [key: string]: unknown;
    };
    /**
     * Error
     */
    error: string | null;
    /**
     * Started At
     */
    started_at: string | null;
    /**
     * Completed At
     */
    completed_at: string | null;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * WorkflowNode
 *
 * ワークフローノード.
 */
export type WorkflowNode = {
    /**
     * Id
     */
    id: string;
    /**
     * Type
     */
    type: string;
    position: NodePosition;
    /**
     * Data
     */
    data?: {
        [key: string]: unknown;
    };
};

/**
 * WorkflowResponse
 *
 * Workflowレスポンス.
 */
export type WorkflowResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * User Id
     */
    user_id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description: string | null;
    /**
     * Nodes
     */
    nodes: Array<{
        [key: string]: unknown;
    }>;
    /**
     * Edges
     */
    edges: Array<{
        [key: string]: unknown;
    }>;
    /**
     * Trigger Config
     */
    trigger_config: {
        [key: string]: unknown;
    };
    /**
     * Is Active
     */
    is_active: boolean;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * WorkflowUpdate
 *
 * Workflow更新リクエスト.
 */
export type WorkflowUpdate = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Nodes
     */
    nodes?: Array<WorkflowNode> | null;
    /**
     * Edges
     */
    edges?: Array<WorkflowEdge> | null;
    /**
     * Trigger Config
     */
    trigger_config?: {
        [key: string]: unknown;
    } | null;
    /**
     * Is Active
     */
    is_active?: boolean | null;
};

export type ListAgentsApiAgentsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/agents';
};

export type ListAgentsApiAgentsGetResponses = {
    /**
     * Response List Agents Api Agents Get
     *
     * Successful Response
     */
    200: Array<AgentResponse>;
};

export type ListAgentsApiAgentsGetResponse = ListAgentsApiAgentsGetResponses[keyof ListAgentsApiAgentsGetResponses];

export type CreateAgentApiAgentsPostData = {
    body: AgentCreate;
    path?: never;
    query?: never;
    url: '/api/agents';
};

export type CreateAgentApiAgentsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateAgentApiAgentsPostError = CreateAgentApiAgentsPostErrors[keyof CreateAgentApiAgentsPostErrors];

export type CreateAgentApiAgentsPostResponses = {
    /**
     * Successful Response
     */
    201: AgentResponse;
};

export type CreateAgentApiAgentsPostResponse = CreateAgentApiAgentsPostResponses[keyof CreateAgentApiAgentsPostResponses];

export type DeleteAgentApiAgentsAgentIdDeleteData = {
    body?: never;
    path: {
        /**
         * Agent Id
         */
        agent_id: string;
    };
    query?: never;
    url: '/api/agents/{agent_id}';
};

export type DeleteAgentApiAgentsAgentIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteAgentApiAgentsAgentIdDeleteError = DeleteAgentApiAgentsAgentIdDeleteErrors[keyof DeleteAgentApiAgentsAgentIdDeleteErrors];

export type DeleteAgentApiAgentsAgentIdDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteAgentApiAgentsAgentIdDeleteResponse = DeleteAgentApiAgentsAgentIdDeleteResponses[keyof DeleteAgentApiAgentsAgentIdDeleteResponses];

export type GetAgentApiAgentsAgentIdGetData = {
    body?: never;
    path: {
        /**
         * Agent Id
         */
        agent_id: string;
    };
    query?: never;
    url: '/api/agents/{agent_id}';
};

export type GetAgentApiAgentsAgentIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetAgentApiAgentsAgentIdGetError = GetAgentApiAgentsAgentIdGetErrors[keyof GetAgentApiAgentsAgentIdGetErrors];

export type GetAgentApiAgentsAgentIdGetResponses = {
    /**
     * Successful Response
     */
    200: AgentResponse;
};

export type GetAgentApiAgentsAgentIdGetResponse = GetAgentApiAgentsAgentIdGetResponses[keyof GetAgentApiAgentsAgentIdGetResponses];

export type UpdateAgentApiAgentsAgentIdPatchData = {
    body: AgentUpdate;
    path: {
        /**
         * Agent Id
         */
        agent_id: string;
    };
    query?: never;
    url: '/api/agents/{agent_id}';
};

export type UpdateAgentApiAgentsAgentIdPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateAgentApiAgentsAgentIdPatchError = UpdateAgentApiAgentsAgentIdPatchErrors[keyof UpdateAgentApiAgentsAgentIdPatchErrors];

export type UpdateAgentApiAgentsAgentIdPatchResponses = {
    /**
     * Successful Response
     */
    200: AgentResponse;
};

export type UpdateAgentApiAgentsAgentIdPatchResponse = UpdateAgentApiAgentsAgentIdPatchResponses[keyof UpdateAgentApiAgentsAgentIdPatchResponses];

export type ListPersonalAgentsApiPersonalAgentsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/personal-agents';
};

export type ListPersonalAgentsApiPersonalAgentsGetResponses = {
    /**
     * Response List Personal Agents Api Personal Agents Get
     *
     * Successful Response
     */
    200: Array<PersonalAgentResponse>;
};

export type ListPersonalAgentsApiPersonalAgentsGetResponse = ListPersonalAgentsApiPersonalAgentsGetResponses[keyof ListPersonalAgentsApiPersonalAgentsGetResponses];

export type CreatePersonalAgentApiPersonalAgentsPostData = {
    body: PersonalAgentCreate;
    path?: never;
    query?: never;
    url: '/api/personal-agents';
};

export type CreatePersonalAgentApiPersonalAgentsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreatePersonalAgentApiPersonalAgentsPostError = CreatePersonalAgentApiPersonalAgentsPostErrors[keyof CreatePersonalAgentApiPersonalAgentsPostErrors];

export type CreatePersonalAgentApiPersonalAgentsPostResponses = {
    /**
     * Successful Response
     */
    201: PersonalAgentResponse;
};

export type CreatePersonalAgentApiPersonalAgentsPostResponse = CreatePersonalAgentApiPersonalAgentsPostResponses[keyof CreatePersonalAgentApiPersonalAgentsPostResponses];

export type DeletePersonalAgentApiPersonalAgentsAgentIdDeleteData = {
    body?: never;
    path: {
        /**
         * Agent Id
         */
        agent_id: string;
    };
    query?: never;
    url: '/api/personal-agents/{agent_id}';
};

export type DeletePersonalAgentApiPersonalAgentsAgentIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeletePersonalAgentApiPersonalAgentsAgentIdDeleteError = DeletePersonalAgentApiPersonalAgentsAgentIdDeleteErrors[keyof DeletePersonalAgentApiPersonalAgentsAgentIdDeleteErrors];

export type DeletePersonalAgentApiPersonalAgentsAgentIdDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeletePersonalAgentApiPersonalAgentsAgentIdDeleteResponse = DeletePersonalAgentApiPersonalAgentsAgentIdDeleteResponses[keyof DeletePersonalAgentApiPersonalAgentsAgentIdDeleteResponses];

export type GetPersonalAgentApiPersonalAgentsAgentIdGetData = {
    body?: never;
    path: {
        /**
         * Agent Id
         */
        agent_id: string;
    };
    query?: never;
    url: '/api/personal-agents/{agent_id}';
};

export type GetPersonalAgentApiPersonalAgentsAgentIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetPersonalAgentApiPersonalAgentsAgentIdGetError = GetPersonalAgentApiPersonalAgentsAgentIdGetErrors[keyof GetPersonalAgentApiPersonalAgentsAgentIdGetErrors];

export type GetPersonalAgentApiPersonalAgentsAgentIdGetResponses = {
    /**
     * Successful Response
     */
    200: PersonalAgentResponse;
};

export type GetPersonalAgentApiPersonalAgentsAgentIdGetResponse = GetPersonalAgentApiPersonalAgentsAgentIdGetResponses[keyof GetPersonalAgentApiPersonalAgentsAgentIdGetResponses];

export type UpdatePersonalAgentApiPersonalAgentsAgentIdPatchData = {
    body: PersonalAgentUpdate;
    path: {
        /**
         * Agent Id
         */
        agent_id: string;
    };
    query?: never;
    url: '/api/personal-agents/{agent_id}';
};

export type UpdatePersonalAgentApiPersonalAgentsAgentIdPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdatePersonalAgentApiPersonalAgentsAgentIdPatchError = UpdatePersonalAgentApiPersonalAgentsAgentIdPatchErrors[keyof UpdatePersonalAgentApiPersonalAgentsAgentIdPatchErrors];

export type UpdatePersonalAgentApiPersonalAgentsAgentIdPatchResponses = {
    /**
     * Successful Response
     */
    200: PersonalAgentResponse;
};

export type UpdatePersonalAgentApiPersonalAgentsAgentIdPatchResponse = UpdatePersonalAgentApiPersonalAgentsAgentIdPatchResponses[keyof UpdatePersonalAgentApiPersonalAgentsAgentIdPatchResponses];

export type ListLlmConfigsApiUserLlmConfigsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/user/llm-configs';
};

export type ListLlmConfigsApiUserLlmConfigsGetResponses = {
    /**
     * Response List Llm Configs Api User Llm Configs Get
     *
     * Successful Response
     */
    200: Array<UserLlmConfigResponse>;
};

export type ListLlmConfigsApiUserLlmConfigsGetResponse = ListLlmConfigsApiUserLlmConfigsGetResponses[keyof ListLlmConfigsApiUserLlmConfigsGetResponses];

export type CreateLlmConfigApiUserLlmConfigsPostData = {
    body: UserLlmConfigCreate;
    path?: never;
    query?: never;
    url: '/api/user/llm-configs';
};

export type CreateLlmConfigApiUserLlmConfigsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateLlmConfigApiUserLlmConfigsPostError = CreateLlmConfigApiUserLlmConfigsPostErrors[keyof CreateLlmConfigApiUserLlmConfigsPostErrors];

export type CreateLlmConfigApiUserLlmConfigsPostResponses = {
    /**
     * Successful Response
     */
    201: UserLlmConfigResponse;
};

export type CreateLlmConfigApiUserLlmConfigsPostResponse = CreateLlmConfigApiUserLlmConfigsPostResponses[keyof CreateLlmConfigApiUserLlmConfigsPostResponses];

export type DeleteLlmConfigApiUserLlmConfigsConfigIdDeleteData = {
    body?: never;
    path: {
        /**
         * Config Id
         */
        config_id: string;
    };
    query?: never;
    url: '/api/user/llm-configs/{config_id}';
};

export type DeleteLlmConfigApiUserLlmConfigsConfigIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteLlmConfigApiUserLlmConfigsConfigIdDeleteError = DeleteLlmConfigApiUserLlmConfigsConfigIdDeleteErrors[keyof DeleteLlmConfigApiUserLlmConfigsConfigIdDeleteErrors];

export type DeleteLlmConfigApiUserLlmConfigsConfigIdDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteLlmConfigApiUserLlmConfigsConfigIdDeleteResponse = DeleteLlmConfigApiUserLlmConfigsConfigIdDeleteResponses[keyof DeleteLlmConfigApiUserLlmConfigsConfigIdDeleteResponses];

export type ListApiKeysApiUserApiKeysGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/user/api-keys';
};

export type ListApiKeysApiUserApiKeysGetResponses = {
    /**
     * Response List Api Keys Api User Api Keys Get
     *
     * Successful Response
     */
    200: Array<UserApiKeyResponse>;
};

export type ListApiKeysApiUserApiKeysGetResponse = ListApiKeysApiUserApiKeysGetResponses[keyof ListApiKeysApiUserApiKeysGetResponses];

export type CreateApiKeyApiUserApiKeysPostData = {
    body: UserApiKeyCreate;
    path?: never;
    query?: never;
    url: '/api/user/api-keys';
};

export type CreateApiKeyApiUserApiKeysPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateApiKeyApiUserApiKeysPostError = CreateApiKeyApiUserApiKeysPostErrors[keyof CreateApiKeyApiUserApiKeysPostErrors];

export type CreateApiKeyApiUserApiKeysPostResponses = {
    /**
     * Successful Response
     */
    201: UserApiKeyCreated;
};

export type CreateApiKeyApiUserApiKeysPostResponse = CreateApiKeyApiUserApiKeysPostResponses[keyof CreateApiKeyApiUserApiKeysPostResponses];

export type DeleteApiKeyApiUserApiKeysKeyIdDeleteData = {
    body?: never;
    path: {
        /**
         * Key Id
         */
        key_id: string;
    };
    query?: never;
    url: '/api/user/api-keys/{key_id}';
};

export type DeleteApiKeyApiUserApiKeysKeyIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteApiKeyApiUserApiKeysKeyIdDeleteError = DeleteApiKeyApiUserApiKeysKeyIdDeleteErrors[keyof DeleteApiKeyApiUserApiKeysKeyIdDeleteErrors];

export type DeleteApiKeyApiUserApiKeysKeyIdDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteApiKeyApiUserApiKeysKeyIdDeleteResponse = DeleteApiKeyApiUserApiKeysKeyIdDeleteResponses[keyof DeleteApiKeyApiUserApiKeysKeyIdDeleteResponses];

export type ListWorkflowsApiWorkflowsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/workflows';
};

export type ListWorkflowsApiWorkflowsGetResponses = {
    /**
     * Response List Workflows Api Workflows Get
     *
     * Successful Response
     */
    200: Array<WorkflowResponse>;
};

export type ListWorkflowsApiWorkflowsGetResponse = ListWorkflowsApiWorkflowsGetResponses[keyof ListWorkflowsApiWorkflowsGetResponses];

export type CreateWorkflowApiWorkflowsPostData = {
    body: WorkflowCreate;
    path?: never;
    query?: never;
    url: '/api/workflows';
};

export type CreateWorkflowApiWorkflowsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateWorkflowApiWorkflowsPostError = CreateWorkflowApiWorkflowsPostErrors[keyof CreateWorkflowApiWorkflowsPostErrors];

export type CreateWorkflowApiWorkflowsPostResponses = {
    /**
     * Successful Response
     */
    201: WorkflowResponse;
};

export type CreateWorkflowApiWorkflowsPostResponse = CreateWorkflowApiWorkflowsPostResponses[keyof CreateWorkflowApiWorkflowsPostResponses];

export type DeleteWorkflowApiWorkflowsWorkflowIdDeleteData = {
    body?: never;
    path: {
        /**
         * Workflow Id
         */
        workflow_id: string;
    };
    query?: never;
    url: '/api/workflows/{workflow_id}';
};

export type DeleteWorkflowApiWorkflowsWorkflowIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteWorkflowApiWorkflowsWorkflowIdDeleteError = DeleteWorkflowApiWorkflowsWorkflowIdDeleteErrors[keyof DeleteWorkflowApiWorkflowsWorkflowIdDeleteErrors];

export type DeleteWorkflowApiWorkflowsWorkflowIdDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteWorkflowApiWorkflowsWorkflowIdDeleteResponse = DeleteWorkflowApiWorkflowsWorkflowIdDeleteResponses[keyof DeleteWorkflowApiWorkflowsWorkflowIdDeleteResponses];

export type GetWorkflowApiWorkflowsWorkflowIdGetData = {
    body?: never;
    path: {
        /**
         * Workflow Id
         */
        workflow_id: string;
    };
    query?: never;
    url: '/api/workflows/{workflow_id}';
};

export type GetWorkflowApiWorkflowsWorkflowIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetWorkflowApiWorkflowsWorkflowIdGetError = GetWorkflowApiWorkflowsWorkflowIdGetErrors[keyof GetWorkflowApiWorkflowsWorkflowIdGetErrors];

export type GetWorkflowApiWorkflowsWorkflowIdGetResponses = {
    /**
     * Successful Response
     */
    200: WorkflowResponse;
};

export type GetWorkflowApiWorkflowsWorkflowIdGetResponse = GetWorkflowApiWorkflowsWorkflowIdGetResponses[keyof GetWorkflowApiWorkflowsWorkflowIdGetResponses];

export type UpdateWorkflowApiWorkflowsWorkflowIdPatchData = {
    body: WorkflowUpdate;
    path: {
        /**
         * Workflow Id
         */
        workflow_id: string;
    };
    query?: never;
    url: '/api/workflows/{workflow_id}';
};

export type UpdateWorkflowApiWorkflowsWorkflowIdPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateWorkflowApiWorkflowsWorkflowIdPatchError = UpdateWorkflowApiWorkflowsWorkflowIdPatchErrors[keyof UpdateWorkflowApiWorkflowsWorkflowIdPatchErrors];

export type UpdateWorkflowApiWorkflowsWorkflowIdPatchResponses = {
    /**
     * Successful Response
     */
    200: WorkflowResponse;
};

export type UpdateWorkflowApiWorkflowsWorkflowIdPatchResponse = UpdateWorkflowApiWorkflowsWorkflowIdPatchResponses[keyof UpdateWorkflowApiWorkflowsWorkflowIdPatchResponses];

export type ExecuteWorkflowApiWorkflowsWorkflowIdExecutePostData = {
    /**
     * Execution Data
     */
    body?: WorkflowExecutionCreate | null;
    path: {
        /**
         * Workflow Id
         */
        workflow_id: string;
    };
    query?: never;
    url: '/api/workflows/{workflow_id}/execute';
};

export type ExecuteWorkflowApiWorkflowsWorkflowIdExecutePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ExecuteWorkflowApiWorkflowsWorkflowIdExecutePostError = ExecuteWorkflowApiWorkflowsWorkflowIdExecutePostErrors[keyof ExecuteWorkflowApiWorkflowsWorkflowIdExecutePostErrors];

export type ExecuteWorkflowApiWorkflowsWorkflowIdExecutePostResponses = {
    /**
     * Successful Response
     */
    202: WorkflowExecutionResponse;
};

export type ExecuteWorkflowApiWorkflowsWorkflowIdExecutePostResponse = ExecuteWorkflowApiWorkflowsWorkflowIdExecutePostResponses[keyof ExecuteWorkflowApiWorkflowsWorkflowIdExecutePostResponses];

export type ListWorkflowExecutionsApiWorkflowsWorkflowIdExecutionsGetData = {
    body?: never;
    path: {
        /**
         * Workflow Id
         */
        workflow_id: string;
    };
    query?: {
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/workflows/{workflow_id}/executions';
};

export type ListWorkflowExecutionsApiWorkflowsWorkflowIdExecutionsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListWorkflowExecutionsApiWorkflowsWorkflowIdExecutionsGetError = ListWorkflowExecutionsApiWorkflowsWorkflowIdExecutionsGetErrors[keyof ListWorkflowExecutionsApiWorkflowsWorkflowIdExecutionsGetErrors];

export type ListWorkflowExecutionsApiWorkflowsWorkflowIdExecutionsGetResponses = {
    /**
     * Response List Workflow Executions Api Workflows  Workflow Id  Executions Get
     *
     * Successful Response
     */
    200: Array<WorkflowExecutionResponse>;
};

export type ListWorkflowExecutionsApiWorkflowsWorkflowIdExecutionsGetResponse = ListWorkflowExecutionsApiWorkflowsWorkflowIdExecutionsGetResponses[keyof ListWorkflowExecutionsApiWorkflowsWorkflowIdExecutionsGetResponses];

export type GetWorkflowExecutionApiWorkflowsWorkflowIdExecutionsExecutionIdGetData = {
    body?: never;
    path: {
        /**
         * Workflow Id
         */
        workflow_id: string;
        /**
         * Execution Id
         */
        execution_id: string;
    };
    query?: never;
    url: '/api/workflows/{workflow_id}/executions/{execution_id}';
};

export type GetWorkflowExecutionApiWorkflowsWorkflowIdExecutionsExecutionIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetWorkflowExecutionApiWorkflowsWorkflowIdExecutionsExecutionIdGetError = GetWorkflowExecutionApiWorkflowsWorkflowIdExecutionsExecutionIdGetErrors[keyof GetWorkflowExecutionApiWorkflowsWorkflowIdExecutionsExecutionIdGetErrors];

export type GetWorkflowExecutionApiWorkflowsWorkflowIdExecutionsExecutionIdGetResponses = {
    /**
     * Successful Response
     */
    200: WorkflowExecutionResponse;
};

export type GetWorkflowExecutionApiWorkflowsWorkflowIdExecutionsExecutionIdGetResponse = GetWorkflowExecutionApiWorkflowsWorkflowIdExecutionsExecutionIdGetResponses[keyof GetWorkflowExecutionApiWorkflowsWorkflowIdExecutionsExecutionIdGetResponses];

export type ChatApiChatPostData = {
    body: ChatRequest;
    path?: never;
    query?: never;
    url: '/api/chat';
};

export type ChatApiChatPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ChatApiChatPostError = ChatApiChatPostErrors[keyof ChatApiChatPostErrors];

export type ChatApiChatPostResponses = {
    /**
     * Successful Response
     */
    200: ChatResponse;
};

export type ChatApiChatPostResponse = ChatApiChatPostResponses[keyof ChatApiChatPostResponses];

export type ChatStreamApiChatStreamPostData = {
    body: ChatRequest;
    path?: never;
    query?: never;
    url: '/api/chat/stream';
};

export type ChatStreamApiChatStreamPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ChatStreamApiChatStreamPostError = ChatStreamApiChatStreamPostErrors[keyof ChatStreamApiChatStreamPostErrors];

export type ChatStreamApiChatStreamPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ChatStreamWithToolsApiChatStreamToolsPostData = {
    body: ChatRequest;
    path?: never;
    query?: never;
    url: '/api/chat/stream/tools';
};

export type ChatStreamWithToolsApiChatStreamToolsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ChatStreamWithToolsApiChatStreamToolsPostError = ChatStreamWithToolsApiChatStreamToolsPostErrors[keyof ChatStreamWithToolsApiChatStreamToolsPostErrors];

export type ChatStreamWithToolsApiChatStreamToolsPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ListConversationsApiChatConversationsGetData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Agent Id
         */
        agent_id: string;
    };
    url: '/api/chat/conversations';
};

export type ListConversationsApiChatConversationsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListConversationsApiChatConversationsGetError = ListConversationsApiChatConversationsGetErrors[keyof ListConversationsApiChatConversationsGetErrors];

export type ListConversationsApiChatConversationsGetResponses = {
    /**
     * Response List Conversations Api Chat Conversations Get
     *
     * Successful Response
     */
    200: Array<ConversationResponse>;
};

export type ListConversationsApiChatConversationsGetResponse = ListConversationsApiChatConversationsGetResponses[keyof ListConversationsApiChatConversationsGetResponses];

export type CreateConversationApiChatConversationsPostData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Agent Id
         */
        agent_id: string;
        /**
         * Title
         */
        title?: string | null;
    };
    url: '/api/chat/conversations';
};

export type CreateConversationApiChatConversationsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateConversationApiChatConversationsPostError = CreateConversationApiChatConversationsPostErrors[keyof CreateConversationApiChatConversationsPostErrors];

export type CreateConversationApiChatConversationsPostResponses = {
    /**
     * Successful Response
     */
    201: ConversationResponse;
};

export type CreateConversationApiChatConversationsPostResponse = CreateConversationApiChatConversationsPostResponses[keyof CreateConversationApiChatConversationsPostResponses];

export type DeleteConversationApiChatConversationsConversationIdDeleteData = {
    body?: never;
    path: {
        /**
         * Conversation Id
         */
        conversation_id: string;
    };
    query?: never;
    url: '/api/chat/conversations/{conversation_id}';
};

export type DeleteConversationApiChatConversationsConversationIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteConversationApiChatConversationsConversationIdDeleteError = DeleteConversationApiChatConversationsConversationIdDeleteErrors[keyof DeleteConversationApiChatConversationsConversationIdDeleteErrors];

export type DeleteConversationApiChatConversationsConversationIdDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteConversationApiChatConversationsConversationIdDeleteResponse = DeleteConversationApiChatConversationsConversationIdDeleteResponses[keyof DeleteConversationApiChatConversationsConversationIdDeleteResponses];

export type GetConversationApiChatConversationsConversationIdGetData = {
    body?: never;
    path: {
        /**
         * Conversation Id
         */
        conversation_id: string;
    };
    query?: never;
    url: '/api/chat/conversations/{conversation_id}';
};

export type GetConversationApiChatConversationsConversationIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetConversationApiChatConversationsConversationIdGetError = GetConversationApiChatConversationsConversationIdGetErrors[keyof GetConversationApiChatConversationsConversationIdGetErrors];

export type GetConversationApiChatConversationsConversationIdGetResponses = {
    /**
     * Successful Response
     */
    200: ConversationWithMessagesResponse;
};

export type GetConversationApiChatConversationsConversationIdGetResponse = GetConversationApiChatConversationsConversationIdGetResponses[keyof GetConversationApiChatConversationsConversationIdGetResponses];

export type GetAgentCardA2aAgentsAgentIdWellKnownAgentJsonGetData = {
    body?: never;
    path: {
        /**
         * Agent Id
         */
        agent_id: string;
    };
    query?: never;
    url: '/a2a/agents/{agent_id}/.well-known/agent.json';
};

export type GetAgentCardA2aAgentsAgentIdWellKnownAgentJsonGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetAgentCardA2aAgentsAgentIdWellKnownAgentJsonGetError = GetAgentCardA2aAgentsAgentIdWellKnownAgentJsonGetErrors[keyof GetAgentCardA2aAgentsAgentIdWellKnownAgentJsonGetErrors];

export type GetAgentCardA2aAgentsAgentIdWellKnownAgentJsonGetResponses = {
    /**
     * Successful Response
     */
    200: AgentCard;
};

export type GetAgentCardA2aAgentsAgentIdWellKnownAgentJsonGetResponse = GetAgentCardA2aAgentsAgentIdWellKnownAgentJsonGetResponses[keyof GetAgentCardA2aAgentsAgentIdWellKnownAgentJsonGetResponses];

export type CreateTaskA2aAgentsAgentIdTasksPostData = {
    body: TaskRequest;
    path: {
        /**
         * Agent Id
         */
        agent_id: string;
    };
    query?: never;
    url: '/a2a/agents/{agent_id}/tasks';
};

export type CreateTaskA2aAgentsAgentIdTasksPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateTaskA2aAgentsAgentIdTasksPostError = CreateTaskA2aAgentsAgentIdTasksPostErrors[keyof CreateTaskA2aAgentsAgentIdTasksPostErrors];

export type CreateTaskA2aAgentsAgentIdTasksPostResponses = {
    /**
     * Successful Response
     */
    200: TaskResponse;
};

export type CreateTaskA2aAgentsAgentIdTasksPostResponse = CreateTaskA2aAgentsAgentIdTasksPostResponses[keyof CreateTaskA2aAgentsAgentIdTasksPostResponses];

export type GetTaskA2aAgentsAgentIdTasksTaskIdGetData = {
    body?: never;
    path: {
        /**
         * Agent Id
         */
        agent_id: string;
        /**
         * Task Id
         */
        task_id: string;
    };
    query?: never;
    url: '/a2a/agents/{agent_id}/tasks/{task_id}';
};

export type GetTaskA2aAgentsAgentIdTasksTaskIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetTaskA2aAgentsAgentIdTasksTaskIdGetError = GetTaskA2aAgentsAgentIdTasksTaskIdGetErrors[keyof GetTaskA2aAgentsAgentIdTasksTaskIdGetErrors];

export type GetTaskA2aAgentsAgentIdTasksTaskIdGetResponses = {
    /**
     * Successful Response
     */
    200: TaskResponse;
};

export type GetTaskA2aAgentsAgentIdTasksTaskIdGetResponse = GetTaskA2aAgentsAgentIdTasksTaskIdGetResponses[keyof GetTaskA2aAgentsAgentIdTasksTaskIdGetResponses];

export type CancelTaskA2aAgentsAgentIdTasksTaskIdCancelPostData = {
    body?: never;
    path: {
        /**
         * Agent Id
         */
        agent_id: string;
        /**
         * Task Id
         */
        task_id: string;
    };
    query?: never;
    url: '/a2a/agents/{agent_id}/tasks/{task_id}/cancel';
};

export type CancelTaskA2aAgentsAgentIdTasksTaskIdCancelPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CancelTaskA2aAgentsAgentIdTasksTaskIdCancelPostError = CancelTaskA2aAgentsAgentIdTasksTaskIdCancelPostErrors[keyof CancelTaskA2aAgentsAgentIdTasksTaskIdCancelPostErrors];

export type CancelTaskA2aAgentsAgentIdTasksTaskIdCancelPostResponses = {
    /**
     * Successful Response
     */
    200: TaskResponse;
};

export type CancelTaskA2aAgentsAgentIdTasksTaskIdCancelPostResponse = CancelTaskA2aAgentsAgentIdTasksTaskIdCancelPostResponses[keyof CancelTaskA2aAgentsAgentIdTasksTaskIdCancelPostResponses];

export type HandleWebhookWebhooksWebhookPathPostData = {
    body?: never;
    path: {
        /**
         * Webhook Path
         */
        webhook_path: string;
    };
    query?: never;
    url: '/webhooks/{webhook_path}';
};

export type HandleWebhookWebhooksWebhookPathPostErrors = {
    /**
     * Unauthorized
     */
    401: WebhookErrorResponse;
    /**
     * Not Found
     */
    404: WebhookErrorResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type HandleWebhookWebhooksWebhookPathPostError = HandleWebhookWebhooksWebhookPathPostErrors[keyof HandleWebhookWebhooksWebhookPathPostErrors];

export type HandleWebhookWebhooksWebhookPathPostResponses = {
    /**
     * Successful Response
     */
    200: WebhookResponse;
};

export type HandleWebhookWebhooksWebhookPathPostResponse = HandleWebhookWebhooksWebhookPathPostResponses[keyof HandleWebhookWebhooksWebhookPathPostResponses];

export type ApiExecuteWorkflowV1ExecuteWorkflowIdPostData = {
    /**
     * Request
     */
    body?: ApiTriggerRequest | null;
    headers: {
        /**
         * X-Api-Key
         */
        'X-API-Key': string;
    };
    path: {
        /**
         * Workflow Id
         */
        workflow_id: string;
    };
    query?: never;
    url: '/v1/execute/{workflow_id}';
};

export type ApiExecuteWorkflowV1ExecuteWorkflowIdPostErrors = {
    /**
     * Unauthorized
     */
    401: ApiTriggerErrorResponse;
    /**
     * Forbidden
     */
    403: ApiTriggerErrorResponse;
    /**
     * Not Found
     */
    404: ApiTriggerErrorResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Too Many Requests
     */
    429: ApiTriggerErrorResponse;
};

export type ApiExecuteWorkflowV1ExecuteWorkflowIdPostError = ApiExecuteWorkflowV1ExecuteWorkflowIdPostErrors[keyof ApiExecuteWorkflowV1ExecuteWorkflowIdPostErrors];

export type ApiExecuteWorkflowV1ExecuteWorkflowIdPostResponses = {
    /**
     * Successful Response
     */
    200: ApiTriggerResponse;
};

export type ApiExecuteWorkflowV1ExecuteWorkflowIdPostResponse = ApiExecuteWorkflowV1ExecuteWorkflowIdPostResponses[keyof ApiExecuteWorkflowV1ExecuteWorkflowIdPostResponses];

export type GetRateLimitStatusV1RateLimitGetData = {
    body?: never;
    headers: {
        /**
         * X-Api-Key
         */
        'X-API-Key': string;
    };
    path?: never;
    query?: never;
    url: '/v1/rate-limit';
};

export type GetRateLimitStatusV1RateLimitGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetRateLimitStatusV1RateLimitGetError = GetRateLimitStatusV1RateLimitGetErrors[keyof GetRateLimitStatusV1RateLimitGetErrors];

export type GetRateLimitStatusV1RateLimitGetResponses = {
    /**
     * Response Get Rate Limit Status V1 Rate Limit Get
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type GetRateLimitStatusV1RateLimitGetResponse = GetRateLimitStatusV1RateLimitGetResponses[keyof GetRateLimitStatusV1RateLimitGetResponses];

export type ListScheduleTriggersApiWorkflowsWorkflowIdTriggersSchedulesGetData = {
    body?: never;
    path: {
        /**
         * Workflow Id
         */
        workflow_id: string;
    };
    query?: never;
    url: '/api/workflows/{workflow_id}/triggers/schedules';
};

export type ListScheduleTriggersApiWorkflowsWorkflowIdTriggersSchedulesGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListScheduleTriggersApiWorkflowsWorkflowIdTriggersSchedulesGetError = ListScheduleTriggersApiWorkflowsWorkflowIdTriggersSchedulesGetErrors[keyof ListScheduleTriggersApiWorkflowsWorkflowIdTriggersSchedulesGetErrors];

export type ListScheduleTriggersApiWorkflowsWorkflowIdTriggersSchedulesGetResponses = {
    /**
     * Response List Schedule Triggers Api Workflows  Workflow Id  Triggers Schedules Get
     *
     * Successful Response
     */
    200: Array<ScheduleTriggerResponse>;
};

export type ListScheduleTriggersApiWorkflowsWorkflowIdTriggersSchedulesGetResponse = ListScheduleTriggersApiWorkflowsWorkflowIdTriggersSchedulesGetResponses[keyof ListScheduleTriggersApiWorkflowsWorkflowIdTriggersSchedulesGetResponses];

export type CreateScheduleTriggerApiWorkflowsWorkflowIdTriggersSchedulesPostData = {
    body: ScheduleTriggerCreate;
    path: {
        /**
         * Workflow Id
         */
        workflow_id: string;
    };
    query?: never;
    url: '/api/workflows/{workflow_id}/triggers/schedules';
};

export type CreateScheduleTriggerApiWorkflowsWorkflowIdTriggersSchedulesPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateScheduleTriggerApiWorkflowsWorkflowIdTriggersSchedulesPostError = CreateScheduleTriggerApiWorkflowsWorkflowIdTriggersSchedulesPostErrors[keyof CreateScheduleTriggerApiWorkflowsWorkflowIdTriggersSchedulesPostErrors];

export type CreateScheduleTriggerApiWorkflowsWorkflowIdTriggersSchedulesPostResponses = {
    /**
     * Successful Response
     */
    201: ScheduleTriggerResponse;
};

export type CreateScheduleTriggerApiWorkflowsWorkflowIdTriggersSchedulesPostResponse = CreateScheduleTriggerApiWorkflowsWorkflowIdTriggersSchedulesPostResponses[keyof CreateScheduleTriggerApiWorkflowsWorkflowIdTriggersSchedulesPostResponses];

export type DeleteScheduleTriggerApiWorkflowsWorkflowIdTriggersSchedulesTriggerIdDeleteData = {
    body?: never;
    path: {
        /**
         * Workflow Id
         */
        workflow_id: string;
        /**
         * Trigger Id
         */
        trigger_id: string;
    };
    query?: never;
    url: '/api/workflows/{workflow_id}/triggers/schedules/{trigger_id}';
};

export type DeleteScheduleTriggerApiWorkflowsWorkflowIdTriggersSchedulesTriggerIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteScheduleTriggerApiWorkflowsWorkflowIdTriggersSchedulesTriggerIdDeleteError = DeleteScheduleTriggerApiWorkflowsWorkflowIdTriggersSchedulesTriggerIdDeleteErrors[keyof DeleteScheduleTriggerApiWorkflowsWorkflowIdTriggersSchedulesTriggerIdDeleteErrors];

export type DeleteScheduleTriggerApiWorkflowsWorkflowIdTriggersSchedulesTriggerIdDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteScheduleTriggerApiWorkflowsWorkflowIdTriggersSchedulesTriggerIdDeleteResponse = DeleteScheduleTriggerApiWorkflowsWorkflowIdTriggersSchedulesTriggerIdDeleteResponses[keyof DeleteScheduleTriggerApiWorkflowsWorkflowIdTriggersSchedulesTriggerIdDeleteResponses];

export type ToggleScheduleTriggerApiWorkflowsWorkflowIdTriggersSchedulesTriggerIdTogglePatchData = {
    body: ScheduleTriggerToggle;
    path: {
        /**
         * Workflow Id
         */
        workflow_id: string;
        /**
         * Trigger Id
         */
        trigger_id: string;
    };
    query?: never;
    url: '/api/workflows/{workflow_id}/triggers/schedules/{trigger_id}/toggle';
};

export type ToggleScheduleTriggerApiWorkflowsWorkflowIdTriggersSchedulesTriggerIdTogglePatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ToggleScheduleTriggerApiWorkflowsWorkflowIdTriggersSchedulesTriggerIdTogglePatchError = ToggleScheduleTriggerApiWorkflowsWorkflowIdTriggersSchedulesTriggerIdTogglePatchErrors[keyof ToggleScheduleTriggerApiWorkflowsWorkflowIdTriggersSchedulesTriggerIdTogglePatchErrors];

export type ToggleScheduleTriggerApiWorkflowsWorkflowIdTriggersSchedulesTriggerIdTogglePatchResponses = {
    /**
     * Successful Response
     */
    200: ScheduleTriggerResponse;
};

export type ToggleScheduleTriggerApiWorkflowsWorkflowIdTriggersSchedulesTriggerIdTogglePatchResponse = ToggleScheduleTriggerApiWorkflowsWorkflowIdTriggersSchedulesTriggerIdTogglePatchResponses[keyof ToggleScheduleTriggerApiWorkflowsWorkflowIdTriggersSchedulesTriggerIdTogglePatchResponses];

export type ListWebhookTriggersApiWorkflowsWorkflowIdTriggersWebhooksGetData = {
    body?: never;
    path: {
        /**
         * Workflow Id
         */
        workflow_id: string;
    };
    query?: never;
    url: '/api/workflows/{workflow_id}/triggers/webhooks';
};

export type ListWebhookTriggersApiWorkflowsWorkflowIdTriggersWebhooksGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListWebhookTriggersApiWorkflowsWorkflowIdTriggersWebhooksGetError = ListWebhookTriggersApiWorkflowsWorkflowIdTriggersWebhooksGetErrors[keyof ListWebhookTriggersApiWorkflowsWorkflowIdTriggersWebhooksGetErrors];

export type ListWebhookTriggersApiWorkflowsWorkflowIdTriggersWebhooksGetResponses = {
    /**
     * Response List Webhook Triggers Api Workflows  Workflow Id  Triggers Webhooks Get
     *
     * Successful Response
     */
    200: Array<WebhookTriggerResponse>;
};

export type ListWebhookTriggersApiWorkflowsWorkflowIdTriggersWebhooksGetResponse = ListWebhookTriggersApiWorkflowsWorkflowIdTriggersWebhooksGetResponses[keyof ListWebhookTriggersApiWorkflowsWorkflowIdTriggersWebhooksGetResponses];

export type CreateWebhookTriggerApiWorkflowsWorkflowIdTriggersWebhooksPostData = {
    body: WebhookTriggerCreate;
    path: {
        /**
         * Workflow Id
         */
        workflow_id: string;
    };
    query?: never;
    url: '/api/workflows/{workflow_id}/triggers/webhooks';
};

export type CreateWebhookTriggerApiWorkflowsWorkflowIdTriggersWebhooksPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateWebhookTriggerApiWorkflowsWorkflowIdTriggersWebhooksPostError = CreateWebhookTriggerApiWorkflowsWorkflowIdTriggersWebhooksPostErrors[keyof CreateWebhookTriggerApiWorkflowsWorkflowIdTriggersWebhooksPostErrors];

export type CreateWebhookTriggerApiWorkflowsWorkflowIdTriggersWebhooksPostResponses = {
    /**
     * Successful Response
     */
    201: WebhookTriggerResponse;
};

export type CreateWebhookTriggerApiWorkflowsWorkflowIdTriggersWebhooksPostResponse = CreateWebhookTriggerApiWorkflowsWorkflowIdTriggersWebhooksPostResponses[keyof CreateWebhookTriggerApiWorkflowsWorkflowIdTriggersWebhooksPostResponses];

export type DeleteWebhookTriggerApiWorkflowsWorkflowIdTriggersWebhooksTriggerIdDeleteData = {
    body?: never;
    path: {
        /**
         * Workflow Id
         */
        workflow_id: string;
        /**
         * Trigger Id
         */
        trigger_id: string;
    };
    query?: never;
    url: '/api/workflows/{workflow_id}/triggers/webhooks/{trigger_id}';
};

export type DeleteWebhookTriggerApiWorkflowsWorkflowIdTriggersWebhooksTriggerIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteWebhookTriggerApiWorkflowsWorkflowIdTriggersWebhooksTriggerIdDeleteError = DeleteWebhookTriggerApiWorkflowsWorkflowIdTriggersWebhooksTriggerIdDeleteErrors[keyof DeleteWebhookTriggerApiWorkflowsWorkflowIdTriggersWebhooksTriggerIdDeleteErrors];

export type DeleteWebhookTriggerApiWorkflowsWorkflowIdTriggersWebhooksTriggerIdDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteWebhookTriggerApiWorkflowsWorkflowIdTriggersWebhooksTriggerIdDeleteResponse = DeleteWebhookTriggerApiWorkflowsWorkflowIdTriggersWebhooksTriggerIdDeleteResponses[keyof DeleteWebhookTriggerApiWorkflowsWorkflowIdTriggersWebhooksTriggerIdDeleteResponses];

export type RegenerateWebhookSecretApiWorkflowsWorkflowIdTriggersWebhooksTriggerIdRegenerateSecretPostData = {
    body?: never;
    path: {
        /**
         * Workflow Id
         */
        workflow_id: string;
        /**
         * Trigger Id
         */
        trigger_id: string;
    };
    query?: never;
    url: '/api/workflows/{workflow_id}/triggers/webhooks/{trigger_id}/regenerate-secret';
};

export type RegenerateWebhookSecretApiWorkflowsWorkflowIdTriggersWebhooksTriggerIdRegenerateSecretPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RegenerateWebhookSecretApiWorkflowsWorkflowIdTriggersWebhooksTriggerIdRegenerateSecretPostError = RegenerateWebhookSecretApiWorkflowsWorkflowIdTriggersWebhooksTriggerIdRegenerateSecretPostErrors[keyof RegenerateWebhookSecretApiWorkflowsWorkflowIdTriggersWebhooksTriggerIdRegenerateSecretPostErrors];

export type RegenerateWebhookSecretApiWorkflowsWorkflowIdTriggersWebhooksTriggerIdRegenerateSecretPostResponses = {
    /**
     * Successful Response
     */
    200: WebhookTriggerSecretResponse;
};

export type RegenerateWebhookSecretApiWorkflowsWorkflowIdTriggersWebhooksTriggerIdRegenerateSecretPostResponse = RegenerateWebhookSecretApiWorkflowsWorkflowIdTriggersWebhooksTriggerIdRegenerateSecretPostResponses[keyof RegenerateWebhookSecretApiWorkflowsWorkflowIdTriggersWebhooksTriggerIdRegenerateSecretPostResponses];

export type RootGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type RootGetResponses = {
    /**
     * Response Root  Get
     *
     * Successful Response
     */
    200: {
        [key: string]: string;
    };
};

export type RootGetResponse = RootGetResponses[keyof RootGetResponses];

export type HealthCheckHealthGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type HealthCheckHealthGetResponses = {
    /**
     * Response Health Check Health Get
     *
     * Successful Response
     */
    200: {
        [key: string]: string;
    };
};

export type HealthCheckHealthGetResponse = HealthCheckHealthGetResponses[keyof HealthCheckHealthGetResponses];
