// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * AgentCard
 *
 * A2A Agent Card.
 */
export type AgentCard = {
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description: string;
    /**
     * Url
     */
    url: string;
    /**
     * Version
     */
    version?: string;
    /**
     * Protocolversion
     */
    protocolVersion?: string;
    /**
     * Capabilities
     */
    capabilities?: {
        [key: string]: unknown;
    };
    /**
     * Skills
     */
    skills?: Array<{
        [key: string]: unknown;
    }>;
    /**
     * Defaultinputmodes
     */
    defaultInputModes?: Array<string>;
    /**
     * Defaultoutputmodes
     */
    defaultOutputModes?: Array<string>;
    /**
     * Provider
     */
    provider?: {
        [key: string]: string;
    } | null;
};

/**
 * AgentCreate
 *
 * エージェント作成リクエスト.
 */
export type AgentCreate = {
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * System Prompt
     */
    system_prompt: string;
    /**
     * Llm Provider
     */
    llm_provider: string;
    /**
     * Llm Model
     */
    llm_model: string;
    /**
     * Tools
     */
    tools?: Array<string>;
    /**
     * A2A Enabled
     */
    a2a_enabled?: boolean;
};

/**
 * AgentResponse
 *
 * エージェントレスポンス.
 */
export type AgentResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * User Id
     */
    user_id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description: string | null;
    /**
     * System Prompt
     */
    system_prompt: string;
    /**
     * Llm Provider
     */
    llm_provider: string;
    /**
     * Llm Model
     */
    llm_model: string;
    /**
     * Tools
     */
    tools: Array<string>;
    /**
     * A2A Enabled
     */
    a2a_enabled: boolean;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * AgentUpdate
 *
 * エージェント更新リクエスト.
 */
export type AgentUpdate = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Description
     */
    description?: string | null;
    /**
     * System Prompt
     */
    system_prompt?: string | null;
    /**
     * Llm Provider
     */
    llm_provider?: string | null;
    /**
     * Llm Model
     */
    llm_model?: string | null;
    /**
     * Tools
     */
    tools?: Array<string> | null;
    /**
     * A2A Enabled
     */
    a2a_enabled?: boolean | null;
};

/**
 * ChatMessageResponse
 *
 * チャットメッセージ.
 */
export type ChatMessageResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Role
     */
    role: string;
    /**
     * Content
     */
    content: string;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * ChatRequest
 *
 * チャットリクエスト.
 */
export type ChatRequest = {
    /**
     * Agent Id
     */
    agent_id: string;
    /**
     * Conversation Id
     */
    conversation_id?: string | null;
    /**
     * Message
     */
    message: string;
};

/**
 * ChatResponse
 *
 * チャットレスポンス.
 */
export type ChatResponse = {
    /**
     * Conversation Id
     */
    conversation_id: string;
    message: ChatMessageResponse;
};

/**
 * ConversationResponse
 *
 * 会話レスポンス.
 */
export type ConversationResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Agent Id
     */
    agent_id: string;
    /**
     * User Id
     */
    user_id: string;
    /**
     * Title
     */
    title: string | null;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * ConversationWithMessagesResponse
 *
 * 会話とメッセージのレスポンス.
 */
export type ConversationWithMessagesResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Agent Id
     */
    agent_id: string;
    /**
     * User Id
     */
    user_id: string;
    /**
     * Title
     */
    title: string | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Messages
     */
    messages: Array<ChatMessageResponse>;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * MessagePart
 *
 * A2Aメッセージパート.
 */
export type MessagePart = {
    /**
     * Type
     */
    type?: string;
    /**
     * Text
     */
    text: string;
};

/**
 * PersonalAgentCreate
 *
 * Personal Agent作成リクエスト.
 */
export type PersonalAgentCreate = {
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * System Prompt
     */
    system_prompt: string;
    /**
     * Is Public
     */
    is_public?: boolean;
};

/**
 * PersonalAgentResponse
 *
 * Personal Agentレスポンス.
 */
export type PersonalAgentResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * User Id
     */
    user_id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description: string | null;
    /**
     * System Prompt
     */
    system_prompt: string;
    /**
     * Is Public
     */
    is_public: boolean;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * PersonalAgentUpdate
 *
 * Personal Agent更新リクエスト.
 */
export type PersonalAgentUpdate = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Description
     */
    description?: string | null;
    /**
     * System Prompt
     */
    system_prompt?: string | null;
    /**
     * Is Public
     */
    is_public?: boolean | null;
};

/**
 * TaskMessage
 *
 * A2Aタスクメッセージ.
 */
export type TaskMessage = {
    /**
     * Role
     */
    role?: string;
    /**
     * Parts
     */
    parts: Array<MessagePart | {
        [key: string]: unknown;
    }>;
};

/**
 * TaskRequest
 *
 * A2Aタスクリクエスト.
 */
export type TaskRequest = {
    /**
     * Id
     */
    id?: string | null;
    message: TaskMessage;
};

/**
 * TaskResponse
 *
 * A2Aタスクレスポンス.
 */
export type TaskResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Status
     */
    status: string;
    result?: TaskResult | null;
    /**
     * Error
     */
    error?: string | null;
    /**
     * Agent Id
     */
    agent_id?: string | null;
};

/**
 * TaskResult
 *
 * A2Aタスク結果.
 */
export type TaskResult = {
    message?: TaskResultMessage | null;
};

/**
 * TaskResultMessage
 *
 * A2Aタスク結果メッセージ.
 */
export type TaskResultMessage = {
    /**
     * Role
     */
    role: string;
    /**
     * Parts
     */
    parts: Array<{
        [key: string]: unknown;
    }>;
};

/**
 * UserApiKeyCreate
 *
 * API Key作成リクエスト.
 */
export type UserApiKeyCreate = {
    /**
     * Name
     */
    name: string;
    /**
     * Scopes
     */
    scopes?: Array<string>;
    /**
     * Rate Limit
     */
    rate_limit?: number;
    /**
     * Expires At
     */
    expires_at?: string | null;
};

/**
 * UserApiKeyCreated
 *
 * API Key作成レスポンス（生キー含む、作成時のみ）.
 */
export type UserApiKeyCreated = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Key
     */
    key: string;
    /**
     * Key Prefix
     */
    key_prefix: string;
    /**
     * Scopes
     */
    scopes: Array<string>;
    /**
     * Rate Limit
     */
    rate_limit: number;
    /**
     * Expires At
     */
    expires_at: string | null;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * UserApiKeyResponse
 *
 * API Keyレスポンス（一覧表示用、生キーなし）.
 */
export type UserApiKeyResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * User Id
     */
    user_id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Key Prefix
     */
    key_prefix: string;
    /**
     * Scopes
     */
    scopes: Array<string>;
    /**
     * Rate Limit
     */
    rate_limit: number;
    /**
     * Expires At
     */
    expires_at: string | null;
    /**
     * Last Used At
     */
    last_used_at: string | null;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * UserLLMConfigCreate
 *
 * LLM Config作成リクエスト.
 */
export type UserLlmConfigCreate = {
    /**
     * Provider
     */
    provider: string;
    /**
     * Api Key
     */
    api_key: string;
    /**
     * Is Default
     */
    is_default?: boolean;
};

/**
 * UserLLMConfigResponse
 *
 * LLM Configレスポンス.
 */
export type UserLlmConfigResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * User Id
     */
    user_id: string;
    /**
     * Provider
     */
    provider: string;
    /**
     * Is Default
     */
    is_default: boolean;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

export type ListAgentsApiAgentsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/agents';
};

export type ListAgentsApiAgentsGetResponses = {
    /**
     * Response List Agents Api Agents Get
     *
     * Successful Response
     */
    200: Array<AgentResponse>;
};

export type ListAgentsApiAgentsGetResponse = ListAgentsApiAgentsGetResponses[keyof ListAgentsApiAgentsGetResponses];

export type CreateAgentApiAgentsPostData = {
    body: AgentCreate;
    path?: never;
    query?: never;
    url: '/api/agents';
};

export type CreateAgentApiAgentsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateAgentApiAgentsPostError = CreateAgentApiAgentsPostErrors[keyof CreateAgentApiAgentsPostErrors];

export type CreateAgentApiAgentsPostResponses = {
    /**
     * Successful Response
     */
    201: AgentResponse;
};

export type CreateAgentApiAgentsPostResponse = CreateAgentApiAgentsPostResponses[keyof CreateAgentApiAgentsPostResponses];

export type DeleteAgentApiAgentsAgentIdDeleteData = {
    body?: never;
    path: {
        /**
         * Agent Id
         */
        agent_id: string;
    };
    query?: never;
    url: '/api/agents/{agent_id}';
};

export type DeleteAgentApiAgentsAgentIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteAgentApiAgentsAgentIdDeleteError = DeleteAgentApiAgentsAgentIdDeleteErrors[keyof DeleteAgentApiAgentsAgentIdDeleteErrors];

export type DeleteAgentApiAgentsAgentIdDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteAgentApiAgentsAgentIdDeleteResponse = DeleteAgentApiAgentsAgentIdDeleteResponses[keyof DeleteAgentApiAgentsAgentIdDeleteResponses];

export type GetAgentApiAgentsAgentIdGetData = {
    body?: never;
    path: {
        /**
         * Agent Id
         */
        agent_id: string;
    };
    query?: never;
    url: '/api/agents/{agent_id}';
};

export type GetAgentApiAgentsAgentIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetAgentApiAgentsAgentIdGetError = GetAgentApiAgentsAgentIdGetErrors[keyof GetAgentApiAgentsAgentIdGetErrors];

export type GetAgentApiAgentsAgentIdGetResponses = {
    /**
     * Successful Response
     */
    200: AgentResponse;
};

export type GetAgentApiAgentsAgentIdGetResponse = GetAgentApiAgentsAgentIdGetResponses[keyof GetAgentApiAgentsAgentIdGetResponses];

export type UpdateAgentApiAgentsAgentIdPatchData = {
    body: AgentUpdate;
    path: {
        /**
         * Agent Id
         */
        agent_id: string;
    };
    query?: never;
    url: '/api/agents/{agent_id}';
};

export type UpdateAgentApiAgentsAgentIdPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateAgentApiAgentsAgentIdPatchError = UpdateAgentApiAgentsAgentIdPatchErrors[keyof UpdateAgentApiAgentsAgentIdPatchErrors];

export type UpdateAgentApiAgentsAgentIdPatchResponses = {
    /**
     * Successful Response
     */
    200: AgentResponse;
};

export type UpdateAgentApiAgentsAgentIdPatchResponse = UpdateAgentApiAgentsAgentIdPatchResponses[keyof UpdateAgentApiAgentsAgentIdPatchResponses];

export type ListPersonalAgentsApiPersonalAgentsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/personal-agents';
};

export type ListPersonalAgentsApiPersonalAgentsGetResponses = {
    /**
     * Response List Personal Agents Api Personal Agents Get
     *
     * Successful Response
     */
    200: Array<PersonalAgentResponse>;
};

export type ListPersonalAgentsApiPersonalAgentsGetResponse = ListPersonalAgentsApiPersonalAgentsGetResponses[keyof ListPersonalAgentsApiPersonalAgentsGetResponses];

export type CreatePersonalAgentApiPersonalAgentsPostData = {
    body: PersonalAgentCreate;
    path?: never;
    query?: never;
    url: '/api/personal-agents';
};

export type CreatePersonalAgentApiPersonalAgentsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreatePersonalAgentApiPersonalAgentsPostError = CreatePersonalAgentApiPersonalAgentsPostErrors[keyof CreatePersonalAgentApiPersonalAgentsPostErrors];

export type CreatePersonalAgentApiPersonalAgentsPostResponses = {
    /**
     * Successful Response
     */
    201: PersonalAgentResponse;
};

export type CreatePersonalAgentApiPersonalAgentsPostResponse = CreatePersonalAgentApiPersonalAgentsPostResponses[keyof CreatePersonalAgentApiPersonalAgentsPostResponses];

export type DeletePersonalAgentApiPersonalAgentsAgentIdDeleteData = {
    body?: never;
    path: {
        /**
         * Agent Id
         */
        agent_id: string;
    };
    query?: never;
    url: '/api/personal-agents/{agent_id}';
};

export type DeletePersonalAgentApiPersonalAgentsAgentIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeletePersonalAgentApiPersonalAgentsAgentIdDeleteError = DeletePersonalAgentApiPersonalAgentsAgentIdDeleteErrors[keyof DeletePersonalAgentApiPersonalAgentsAgentIdDeleteErrors];

export type DeletePersonalAgentApiPersonalAgentsAgentIdDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeletePersonalAgentApiPersonalAgentsAgentIdDeleteResponse = DeletePersonalAgentApiPersonalAgentsAgentIdDeleteResponses[keyof DeletePersonalAgentApiPersonalAgentsAgentIdDeleteResponses];

export type GetPersonalAgentApiPersonalAgentsAgentIdGetData = {
    body?: never;
    path: {
        /**
         * Agent Id
         */
        agent_id: string;
    };
    query?: never;
    url: '/api/personal-agents/{agent_id}';
};

export type GetPersonalAgentApiPersonalAgentsAgentIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetPersonalAgentApiPersonalAgentsAgentIdGetError = GetPersonalAgentApiPersonalAgentsAgentIdGetErrors[keyof GetPersonalAgentApiPersonalAgentsAgentIdGetErrors];

export type GetPersonalAgentApiPersonalAgentsAgentIdGetResponses = {
    /**
     * Successful Response
     */
    200: PersonalAgentResponse;
};

export type GetPersonalAgentApiPersonalAgentsAgentIdGetResponse = GetPersonalAgentApiPersonalAgentsAgentIdGetResponses[keyof GetPersonalAgentApiPersonalAgentsAgentIdGetResponses];

export type UpdatePersonalAgentApiPersonalAgentsAgentIdPatchData = {
    body: PersonalAgentUpdate;
    path: {
        /**
         * Agent Id
         */
        agent_id: string;
    };
    query?: never;
    url: '/api/personal-agents/{agent_id}';
};

export type UpdatePersonalAgentApiPersonalAgentsAgentIdPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdatePersonalAgentApiPersonalAgentsAgentIdPatchError = UpdatePersonalAgentApiPersonalAgentsAgentIdPatchErrors[keyof UpdatePersonalAgentApiPersonalAgentsAgentIdPatchErrors];

export type UpdatePersonalAgentApiPersonalAgentsAgentIdPatchResponses = {
    /**
     * Successful Response
     */
    200: PersonalAgentResponse;
};

export type UpdatePersonalAgentApiPersonalAgentsAgentIdPatchResponse = UpdatePersonalAgentApiPersonalAgentsAgentIdPatchResponses[keyof UpdatePersonalAgentApiPersonalAgentsAgentIdPatchResponses];

export type ListLlmConfigsApiUserLlmConfigsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/user/llm-configs';
};

export type ListLlmConfigsApiUserLlmConfigsGetResponses = {
    /**
     * Response List Llm Configs Api User Llm Configs Get
     *
     * Successful Response
     */
    200: Array<UserLlmConfigResponse>;
};

export type ListLlmConfigsApiUserLlmConfigsGetResponse = ListLlmConfigsApiUserLlmConfigsGetResponses[keyof ListLlmConfigsApiUserLlmConfigsGetResponses];

export type CreateLlmConfigApiUserLlmConfigsPostData = {
    body: UserLlmConfigCreate;
    path?: never;
    query?: never;
    url: '/api/user/llm-configs';
};

export type CreateLlmConfigApiUserLlmConfigsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateLlmConfigApiUserLlmConfigsPostError = CreateLlmConfigApiUserLlmConfigsPostErrors[keyof CreateLlmConfigApiUserLlmConfigsPostErrors];

export type CreateLlmConfigApiUserLlmConfigsPostResponses = {
    /**
     * Successful Response
     */
    201: UserLlmConfigResponse;
};

export type CreateLlmConfigApiUserLlmConfigsPostResponse = CreateLlmConfigApiUserLlmConfigsPostResponses[keyof CreateLlmConfigApiUserLlmConfigsPostResponses];

export type DeleteLlmConfigApiUserLlmConfigsConfigIdDeleteData = {
    body?: never;
    path: {
        /**
         * Config Id
         */
        config_id: string;
    };
    query?: never;
    url: '/api/user/llm-configs/{config_id}';
};

export type DeleteLlmConfigApiUserLlmConfigsConfigIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteLlmConfigApiUserLlmConfigsConfigIdDeleteError = DeleteLlmConfigApiUserLlmConfigsConfigIdDeleteErrors[keyof DeleteLlmConfigApiUserLlmConfigsConfigIdDeleteErrors];

export type DeleteLlmConfigApiUserLlmConfigsConfigIdDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteLlmConfigApiUserLlmConfigsConfigIdDeleteResponse = DeleteLlmConfigApiUserLlmConfigsConfigIdDeleteResponses[keyof DeleteLlmConfigApiUserLlmConfigsConfigIdDeleteResponses];

export type ListApiKeysApiUserApiKeysGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/user/api-keys';
};

export type ListApiKeysApiUserApiKeysGetResponses = {
    /**
     * Response List Api Keys Api User Api Keys Get
     *
     * Successful Response
     */
    200: Array<UserApiKeyResponse>;
};

export type ListApiKeysApiUserApiKeysGetResponse = ListApiKeysApiUserApiKeysGetResponses[keyof ListApiKeysApiUserApiKeysGetResponses];

export type CreateApiKeyApiUserApiKeysPostData = {
    body: UserApiKeyCreate;
    path?: never;
    query?: never;
    url: '/api/user/api-keys';
};

export type CreateApiKeyApiUserApiKeysPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateApiKeyApiUserApiKeysPostError = CreateApiKeyApiUserApiKeysPostErrors[keyof CreateApiKeyApiUserApiKeysPostErrors];

export type CreateApiKeyApiUserApiKeysPostResponses = {
    /**
     * Successful Response
     */
    201: UserApiKeyCreated;
};

export type CreateApiKeyApiUserApiKeysPostResponse = CreateApiKeyApiUserApiKeysPostResponses[keyof CreateApiKeyApiUserApiKeysPostResponses];

export type DeleteApiKeyApiUserApiKeysKeyIdDeleteData = {
    body?: never;
    path: {
        /**
         * Key Id
         */
        key_id: string;
    };
    query?: never;
    url: '/api/user/api-keys/{key_id}';
};

export type DeleteApiKeyApiUserApiKeysKeyIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteApiKeyApiUserApiKeysKeyIdDeleteError = DeleteApiKeyApiUserApiKeysKeyIdDeleteErrors[keyof DeleteApiKeyApiUserApiKeysKeyIdDeleteErrors];

export type DeleteApiKeyApiUserApiKeysKeyIdDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteApiKeyApiUserApiKeysKeyIdDeleteResponse = DeleteApiKeyApiUserApiKeysKeyIdDeleteResponses[keyof DeleteApiKeyApiUserApiKeysKeyIdDeleteResponses];

export type ChatApiChatPostData = {
    body: ChatRequest;
    path?: never;
    query?: never;
    url: '/api/chat';
};

export type ChatApiChatPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ChatApiChatPostError = ChatApiChatPostErrors[keyof ChatApiChatPostErrors];

export type ChatApiChatPostResponses = {
    /**
     * Successful Response
     */
    200: ChatResponse;
};

export type ChatApiChatPostResponse = ChatApiChatPostResponses[keyof ChatApiChatPostResponses];

export type ChatStreamApiChatStreamPostData = {
    body: ChatRequest;
    path?: never;
    query?: never;
    url: '/api/chat/stream';
};

export type ChatStreamApiChatStreamPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ChatStreamApiChatStreamPostError = ChatStreamApiChatStreamPostErrors[keyof ChatStreamApiChatStreamPostErrors];

export type ChatStreamApiChatStreamPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ChatStreamWithToolsApiChatStreamToolsPostData = {
    body: ChatRequest;
    path?: never;
    query?: never;
    url: '/api/chat/stream/tools';
};

export type ChatStreamWithToolsApiChatStreamToolsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ChatStreamWithToolsApiChatStreamToolsPostError = ChatStreamWithToolsApiChatStreamToolsPostErrors[keyof ChatStreamWithToolsApiChatStreamToolsPostErrors];

export type ChatStreamWithToolsApiChatStreamToolsPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ListConversationsApiChatConversationsGetData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Agent Id
         */
        agent_id: string;
    };
    url: '/api/chat/conversations';
};

export type ListConversationsApiChatConversationsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListConversationsApiChatConversationsGetError = ListConversationsApiChatConversationsGetErrors[keyof ListConversationsApiChatConversationsGetErrors];

export type ListConversationsApiChatConversationsGetResponses = {
    /**
     * Response List Conversations Api Chat Conversations Get
     *
     * Successful Response
     */
    200: Array<ConversationResponse>;
};

export type ListConversationsApiChatConversationsGetResponse = ListConversationsApiChatConversationsGetResponses[keyof ListConversationsApiChatConversationsGetResponses];

export type CreateConversationApiChatConversationsPostData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Agent Id
         */
        agent_id: string;
        /**
         * Title
         */
        title?: string | null;
    };
    url: '/api/chat/conversations';
};

export type CreateConversationApiChatConversationsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateConversationApiChatConversationsPostError = CreateConversationApiChatConversationsPostErrors[keyof CreateConversationApiChatConversationsPostErrors];

export type CreateConversationApiChatConversationsPostResponses = {
    /**
     * Successful Response
     */
    201: ConversationResponse;
};

export type CreateConversationApiChatConversationsPostResponse = CreateConversationApiChatConversationsPostResponses[keyof CreateConversationApiChatConversationsPostResponses];

export type DeleteConversationApiChatConversationsConversationIdDeleteData = {
    body?: never;
    path: {
        /**
         * Conversation Id
         */
        conversation_id: string;
    };
    query?: never;
    url: '/api/chat/conversations/{conversation_id}';
};

export type DeleteConversationApiChatConversationsConversationIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteConversationApiChatConversationsConversationIdDeleteError = DeleteConversationApiChatConversationsConversationIdDeleteErrors[keyof DeleteConversationApiChatConversationsConversationIdDeleteErrors];

export type DeleteConversationApiChatConversationsConversationIdDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteConversationApiChatConversationsConversationIdDeleteResponse = DeleteConversationApiChatConversationsConversationIdDeleteResponses[keyof DeleteConversationApiChatConversationsConversationIdDeleteResponses];

export type GetConversationApiChatConversationsConversationIdGetData = {
    body?: never;
    path: {
        /**
         * Conversation Id
         */
        conversation_id: string;
    };
    query?: never;
    url: '/api/chat/conversations/{conversation_id}';
};

export type GetConversationApiChatConversationsConversationIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetConversationApiChatConversationsConversationIdGetError = GetConversationApiChatConversationsConversationIdGetErrors[keyof GetConversationApiChatConversationsConversationIdGetErrors];

export type GetConversationApiChatConversationsConversationIdGetResponses = {
    /**
     * Successful Response
     */
    200: ConversationWithMessagesResponse;
};

export type GetConversationApiChatConversationsConversationIdGetResponse = GetConversationApiChatConversationsConversationIdGetResponses[keyof GetConversationApiChatConversationsConversationIdGetResponses];

export type GetAgentCardA2aAgentsAgentIdWellKnownAgentJsonGetData = {
    body?: never;
    path: {
        /**
         * Agent Id
         */
        agent_id: string;
    };
    query?: never;
    url: '/a2a/agents/{agent_id}/.well-known/agent.json';
};

export type GetAgentCardA2aAgentsAgentIdWellKnownAgentJsonGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetAgentCardA2aAgentsAgentIdWellKnownAgentJsonGetError = GetAgentCardA2aAgentsAgentIdWellKnownAgentJsonGetErrors[keyof GetAgentCardA2aAgentsAgentIdWellKnownAgentJsonGetErrors];

export type GetAgentCardA2aAgentsAgentIdWellKnownAgentJsonGetResponses = {
    /**
     * Successful Response
     */
    200: AgentCard;
};

export type GetAgentCardA2aAgentsAgentIdWellKnownAgentJsonGetResponse = GetAgentCardA2aAgentsAgentIdWellKnownAgentJsonGetResponses[keyof GetAgentCardA2aAgentsAgentIdWellKnownAgentJsonGetResponses];

export type CreateTaskA2aAgentsAgentIdTasksPostData = {
    body: TaskRequest;
    path: {
        /**
         * Agent Id
         */
        agent_id: string;
    };
    query?: never;
    url: '/a2a/agents/{agent_id}/tasks';
};

export type CreateTaskA2aAgentsAgentIdTasksPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateTaskA2aAgentsAgentIdTasksPostError = CreateTaskA2aAgentsAgentIdTasksPostErrors[keyof CreateTaskA2aAgentsAgentIdTasksPostErrors];

export type CreateTaskA2aAgentsAgentIdTasksPostResponses = {
    /**
     * Successful Response
     */
    200: TaskResponse;
};

export type CreateTaskA2aAgentsAgentIdTasksPostResponse = CreateTaskA2aAgentsAgentIdTasksPostResponses[keyof CreateTaskA2aAgentsAgentIdTasksPostResponses];

export type GetTaskA2aAgentsAgentIdTasksTaskIdGetData = {
    body?: never;
    path: {
        /**
         * Agent Id
         */
        agent_id: string;
        /**
         * Task Id
         */
        task_id: string;
    };
    query?: never;
    url: '/a2a/agents/{agent_id}/tasks/{task_id}';
};

export type GetTaskA2aAgentsAgentIdTasksTaskIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetTaskA2aAgentsAgentIdTasksTaskIdGetError = GetTaskA2aAgentsAgentIdTasksTaskIdGetErrors[keyof GetTaskA2aAgentsAgentIdTasksTaskIdGetErrors];

export type GetTaskA2aAgentsAgentIdTasksTaskIdGetResponses = {
    /**
     * Successful Response
     */
    200: TaskResponse;
};

export type GetTaskA2aAgentsAgentIdTasksTaskIdGetResponse = GetTaskA2aAgentsAgentIdTasksTaskIdGetResponses[keyof GetTaskA2aAgentsAgentIdTasksTaskIdGetResponses];

export type CancelTaskA2aAgentsAgentIdTasksTaskIdCancelPostData = {
    body?: never;
    path: {
        /**
         * Agent Id
         */
        agent_id: string;
        /**
         * Task Id
         */
        task_id: string;
    };
    query?: never;
    url: '/a2a/agents/{agent_id}/tasks/{task_id}/cancel';
};

export type CancelTaskA2aAgentsAgentIdTasksTaskIdCancelPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CancelTaskA2aAgentsAgentIdTasksTaskIdCancelPostError = CancelTaskA2aAgentsAgentIdTasksTaskIdCancelPostErrors[keyof CancelTaskA2aAgentsAgentIdTasksTaskIdCancelPostErrors];

export type CancelTaskA2aAgentsAgentIdTasksTaskIdCancelPostResponses = {
    /**
     * Successful Response
     */
    200: TaskResponse;
};

export type CancelTaskA2aAgentsAgentIdTasksTaskIdCancelPostResponse = CancelTaskA2aAgentsAgentIdTasksTaskIdCancelPostResponses[keyof CancelTaskA2aAgentsAgentIdTasksTaskIdCancelPostResponses];

export type RootGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type RootGetResponses = {
    /**
     * Response Root  Get
     *
     * Successful Response
     */
    200: {
        [key: string]: string;
    };
};

export type RootGetResponse = RootGetResponses[keyof RootGetResponses];

export type HealthCheckHealthGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type HealthCheckHealthGetResponses = {
    /**
     * Response Health Check Health Get
     *
     * Successful Response
     */
    200: {
        [key: string]: string;
    };
};

export type HealthCheckHealthGetResponse = HealthCheckHealthGetResponses[keyof HealthCheckHealthGetResponses];
