"""add_phase7_tables

Revision ID: 18930377a226
Revises: dbbba02798e2
Create Date: 2025-12-03 10:34:06.742039

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '18930377a226'
down_revision: str | Sequence[str] | None = 'dbbba02798e2'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('personal_agents',
    sa.Column('id', sa.CHAR(36), nullable=False),
    sa.Column('user_id', sa.CHAR(36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('system_prompt', sa.Text(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column(
        'created_at', sa.DateTime(timezone=True),
        server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False
    ),
    sa.Column(
        'updated_at', sa.DateTime(timezone=True),
        server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False
    ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(
        op.f('ix_personal_agents_user_id'), 'personal_agents', ['user_id'], unique=False
    )
    op.create_table('user_api_keys',
    sa.Column('id', sa.CHAR(36), nullable=False),
    sa.Column('user_id', sa.CHAR(36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.Column('key_prefix', sa.String(length=12), nullable=False),
    sa.Column('scopes', sa.JSON(), nullable=False),
    sa.Column('rate_limit', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column(
        'created_at', sa.DateTime(timezone=True),
        server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False
    ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_api_keys_user_id'), 'user_api_keys', ['user_id'], unique=False)
    op.create_table('user_llm_configs',
    sa.Column('id', sa.CHAR(36), nullable=False),
    sa.Column('user_id', sa.CHAR(36), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('vault_secret_id', sa.String(length=255), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column(
        'created_at', sa.DateTime(timezone=True),
        server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False
    ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'provider', name='uq_user_llm_config_user_provider')
    )
    op.create_index(
        op.f('ix_user_llm_configs_user_id'), 'user_llm_configs', ['user_id'], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_llm_configs_user_id'), table_name='user_llm_configs')
    op.drop_table('user_llm_configs')
    op.drop_index(op.f('ix_user_api_keys_user_id'), table_name='user_api_keys')
    op.drop_table('user_api_keys')
    op.drop_index(op.f('ix_personal_agents_user_id'), table_name='personal_agents')
    op.drop_table('personal_agents')
    # ### end Alembic commands ###
