"""add_is_public_to_agents

Revision ID: 79490d3775db
Revises: cc9d268ce0da
Create Date: 2025-12-03 15:52:47.488488

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79490d3775db'
down_revision: Union[str, Sequence[str], None] = 'cc9d268ce0da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('is_public', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agents', 'is_public')
    # ### end Alembic commands ###
