"""add_workflow_tables

Revision ID: 8bf42ba2e6d8
Revises: 18930377a226
Create Date: 2025-12-03 12:20:13.199200

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '8bf42ba2e6d8'
down_revision: str | Sequence[str] | None = '18930377a226'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workflows',
    sa.Column('id', sa.CHAR(36), nullable=False),
    sa.Column('user_id', sa.CHAR(36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('nodes', sa.JSON(), nullable=False),
    sa.Column('edges', sa.JSON(), nullable=False),
    sa.Column('trigger_config', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column(
        'created_at', sa.DateTime(timezone=True),
        server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False
    ),
    sa.Column(
        'updated_at', sa.DateTime(timezone=True),
        server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False
    ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflows_user_id'), 'workflows', ['user_id'], unique=False)
    op.create_table('workflow_executions',
    sa.Column('id', sa.CHAR(36), nullable=False),
    sa.Column('workflow_id', sa.CHAR(36), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('trigger_data', sa.JSON(), nullable=True),
    sa.Column('node_results', sa.JSON(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column(
        'created_at', sa.DateTime(timezone=True),
        server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False
    ),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(
        op.f('ix_workflow_executions_workflow_id'),
        'workflow_executions', ['workflow_id'], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workflow_executions_workflow_id'), table_name='workflow_executions')
    op.drop_table('workflow_executions')
    op.drop_index(op.f('ix_workflows_user_id'), table_name='workflows')
    op.drop_table('workflows')
    # ### end Alembic commands ###
