"""add_trigger_tables

Revision ID: cc9d268ce0da
Revises: 8bf42ba2e6d8
Create Date: 2025-12-03 14:47:58.281586

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'cc9d268ce0da'
down_revision: str | Sequence[str] | None = '8bf42ba2e6d8'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table(
        'schedule_triggers',
        sa.Column('id', sa.CHAR(36), nullable=False),
        sa.Column('workflow_id', sa.CHAR(36), nullable=False),
        sa.Column('cron_expression', sa.String(length=100), nullable=False),
        sa.Column('timezone', sa.String(length=50), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            'created_at', sa.DateTime(timezone=True),
            server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False
        ),
        sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(
        op.f('ix_schedule_triggers_workflow_id'), 'schedule_triggers', ['workflow_id'], unique=False
    )

    op.create_table(
        'webhook_triggers',
        sa.Column('id', sa.CHAR(36), nullable=False),
        sa.Column('workflow_id', sa.CHAR(36), nullable=False),
        sa.Column('webhook_path', sa.String(length=255), nullable=False),
        sa.Column('secret', sa.String(length=255), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('last_triggered_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            'created_at', sa.DateTime(timezone=True),
            server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False
        ),
        sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('webhook_path')
    )
    op.create_index(
        op.f('ix_webhook_triggers_workflow_id'), 'webhook_triggers', ['workflow_id'], unique=False
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_webhook_triggers_workflow_id'), table_name='webhook_triggers')
    op.drop_table('webhook_triggers')
    op.drop_index(op.f('ix_schedule_triggers_workflow_id'), table_name='schedule_triggers')
    op.drop_table('schedule_triggers')
    # ### end Alembic commands ###
